[project]
name = "arch_agent"
version = "0.1.0"
description = "arch_agent using crewAI"
authors = [
    { name = "Your Name", email = "you@example.com" },
]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.6.0",
    "pymongo==4.16.0",
]

[project.scripts]
arch_agent = "arch_agent.main:run"
run_crew = "arch_agent.main:run"
train = "arch_agent.main:train"
replay = "arch_agent.main:replay"
test = "arch_agent.main:test"
run_with_trigger = "arch_agent.main:run_with_trigger"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
