import test from "node:test";
import assert from "node:assert/strict";

import { extractMermaidSource, isLikelyMermaidDiagram } from "./mermaid-detection.ts";

test("extractMermaidSource recognizes bare mermaid files produced without markdown fences", () => {
  const content = `
flowchart TD
%% ========== External Entities ==========
Player[玩家]
Host[浏览器宿主环境]
Player -->|开始游戏| Host
  `;

  assert.equal(
    extractMermaidSource(content),
    [
      "flowchart TD",
      "%% ========== External Entities ==========",
      "Player[玩家]",
      "Host[浏览器宿主环境]",
      "Player -->|开始游戏| Host",
    ].join("\n"),
  );
});

test("extractMermaidSource recognizes fenced mermaid markdown blocks", () => {
  const content = `
\`\`\`mermaid
sequenceDiagram
Alice->>Bob: Hello
\`\`\`
  `;

  assert.equal(
    extractMermaidSource(content),
    [
      "sequenceDiagram",
      "Alice->>Bob: Hello",
    ].join("\n"),
  );
});

test("extractMermaidSource ignores normal markdown documents", () => {
  const content = `
# Business Scope

- 项目目标
- 成功标准
  `;

  assert.equal(extractMermaidSource(content), null);
  assert.equal(isLikelyMermaidDiagram(content), false);
});

test("extractMermaidSource accepts leading mermaid comments before the diagram header", () => {
  const content = `
%% generated by requirements agent
%% keep this file in markdown
erDiagram
User ||--o{ Session : owns
  `;

  assert.equal(
    extractMermaidSource(content),
    [
      "%% generated by requirements agent",
      "%% keep this file in markdown",
      "erDiagram",
      "User ||--o{ Session : owns",
    ].join("\n"),
  );
});
