from __future__ import annotations

from typing import Any, Literal


Locale = Literal["en", "zh"]
DEFAULT_LOCALE: Locale = "en"


_TRANSLATIONS: dict[Locale, dict[str, str]] = {
    "en": {
        "artifact_review.title": "Generated Drafts",
        "artifact_review.message": "The core drafts are ready. Review them in the artifact panel, then approve them to start code generation or request changes.",
        "artifact_review.confirm": "Approve Drafts & Start Code",
        "artifact_review.cancel": "Modify",
        "artifact_review.content": "Please review the generated drafts and confirm whether to start code generation.",
        "artifact_review.option.prd.label": "PRD Draft",
        "artifact_review.option.prd.description": "Product requirements, scope, and user stories draft.",
        "artifact_review.option.ui.label": "UI Draft",
        "artifact_review.option.ui.description": "Page inventory and primary interaction draft.",
        "artifact_review.option.architecture.label": "Architecture Draft",
        "artifact_review.option.architecture.description": "Service boundaries and technical architecture draft.",
        "artifact_review.option.api_spec.label": "API Design",
        "artifact_review.option.api_spec.description": "Core backend API contract draft.",
        "requirements_artifact_review.title": "Requirements Drafts Ready",
        "requirements_artifact_review.message": "The Requirements Agent has finished the requirement source files. Review the main files first, then confirm to continue with the Architecture Agent.",
        "requirements_artifact_review.message_with_files": "The Requirements Agent has finished the requirement source files. Review {files} first, then confirm to continue with the Architecture Agent.",
        "requirements_artifact_review.confirm": "Approve Requirements Drafts & Continue",
        "requirements_artifact_review.cancel": "Modify",
        "requirements_artifact_review.content": "Please review the generated requirements source files and confirm whether the Architecture Agent should continue.",
        "input_variables.title": "Configure Runtime Variables",
        "input_variables.message": "The code generation agent needs runtime configuration before it can continue with the real coding flow.",
        "input_variables.submit": "Continue",
        "input_variables.skip": "Skip and Use Fallbacks",
        "input_variables.content": "Please provide the runtime variables required to continue code generation.",
        "requirements_feedback.title": "Requirements Agent Needs Feedback",
        "requirements_feedback.message": "Review the generated main requirement files first, then tell the agent what should change and which file should be revised.",
        "requirements_feedback.message_with_files": "Review {files} first, then tell the agent what should change and which file should be revised.",
        "requirements_feedback.field_label": "Feedback",
        "requirements_feedback.placeholder": "Describe what should change. Leave empty if no changes are needed.",
        "requirements_feedback.submit": "Submit Feedback",
        "requirements_feedback.skip": "No Changes Needed",
        "requirements_feedback.content": "Please review the generated requirements draft and send feedback back to the Requirements Agent.",
        "requirements_feedback.resumed": "Requirements Agent resumed after receiving your feedback",
        "coverage_conflict.title": "Overwrite Confirmation",
        "coverage_conflict.message": "This action will overwrite the current project artifacts. Confirm before continuing.",
        "coverage_conflict.option.label": "Confirm Overwrite",
        "coverage_conflict.option.description": "Continue and replace the current artifact set with the updated output.",
        "coverage_conflict.confirm": "Confirm Overwrite",
        "coverage_conflict.cancel": "Cancel",
        "coverage_conflict.content": "Please confirm that the current artifacts can be overwritten before continuing.",
        "feature_modules.title": "Feature Modules",
        "feature_modules.confirm": "Confirm & Continue",
        "feature_modules.cancel": "Modify",
        "feature_modules.content": "Please review feature_tree.md and confirm whether this feature tree should be used to continue.",
        "waiting.message": "Agent is waiting for your response",
        "task.completed.modify": "The requested changes have been applied to the latest project drafts.",
        "task.completed.review": "The approved drafts have now been used to generate the code workspace. This round is complete.",
        "task.cancelled": "The current task was cancelled.",
        "error.no_confirmed_modules": "No confirmed feature modules are available for this project yet. Complete the initial generation first.",
        "error.runtime_context_missing": "Runtime variable request context is missing.",
        "error.runtime_resume_missing": "Runtime variable request could not resume the pending task.",
        "error.feedback_resume_direct_only": "This waiting step must resume through the feedback form.",
        "error.feedback_context_missing": "The pending requirements feedback context is missing.",
        "error.feedback_session_missing": "The waiting Requirements Agent session is no longer available.",
        "error.overwrite_not_approved": "Overwrite confirmation was not approved.",
        "error.pending_overwrite_missing": "The pending overwrite task could not be found.",
        "error.unsupported_overwrite_task_type": "Unsupported overwrite confirmation task type `{task_type}`.",
        "process.reading_context.name": "Reading context",
        "process.reading_context.running": "Reading the prompt and attached references before analysis.",
        "process.reading_context.completed": "Read the prompt and available reference context.",
        "process.requirements_analysis.name": "Analyzing requirements",
        "process.requirements_analysis.running": "Analyzing the requirement and extracting the suggested feature modules.",
        "process.requirements_analysis.completed": "Analyzed the requirement and extracted the suggested feature modules.",
        "process.artifact_generation.name": "Generating core artifacts",
        "process.artifact_generation.running": "Generating the PRD, UI, architecture, and API drafts for review.",
        "process.artifact_generation.completed": "Generated the PRD, UI, architecture, and API drafts for review.",
        "process.requirements_drafts.name": "Generating requirements drafts",
        "process.requirements_drafts.running": "Generating the requirements draft files needed for PRD, UI, and API review.",
        "process.requirements_drafts.waiting": "Waiting for your feedback before continuing the requirements drafts.",
        "process.requirements_drafts.resumed": "Received your feedback and resumed generating the requirements drafts.",
        "process.requirements_drafts.completed": "Generated the requirements draft files for review.",
        "process.requirements_artifact_review.name": "Waiting for requirements draft review",
        "process.requirements_artifact_review.waiting": "The requirements drafts are ready. Confirm them to start the Architecture Agent.",
        "process.architecture_generation.name": "Generating architecture draft",
        "process.architecture_generation.running": "Generating the architecture draft files for review.",
        "process.architecture_generation.completed": "Generated the architecture draft files for review.",
        "process.artifact_review.name": "Waiting for architecture draft review",
        "process.artifact_review.waiting": "The reviewed drafts are ready. Confirm them to start the UI, coding, and test stages.",
        "process.ui_generation.name": "Generating UI workspace",
        "process.ui_generation.review.running": "Generating the UI workspace from the approved drafts.",
        "process.ui_generation.review.completed": "Generated the UI workspace from the approved drafts.",
        "process.ui_generation.runtime.running": "Generating the UI workspace using the provided runtime variables.",
        "process.ui_generation.runtime.completed": "Generated the UI workspace using the provided runtime variables.",
        "process.ui_generation.modify.running": "Regenerating the UI workspace from the updated drafts.",
        "process.ui_generation.modify.completed": "Regenerated the UI workspace from the updated drafts.",
        "process.code_generation.name": "Generating code workspace",
        "process.code_generation.review.running": "Generating the backend code workspace from the approved drafts.",
        "process.code_generation.review.completed": "Generated the backend code workspace from the approved drafts.",
        "process.code_generation.runtime.running": "Generating the backend code workspace using the provided runtime variables.",
        "process.code_generation.runtime.completed": "Generated the backend code workspace using the provided runtime variables.",
        "process.code_generation.modify.running": "Regenerating the backend code workspace from the updated drafts.",
        "process.code_generation.modify.completed": "Regenerated the backend code workspace from the updated drafts.",
        "process.test_generation.name": "Generating test workspace",
        "process.test_generation.review.running": "Generating the test workspace from the approved drafts.",
        "process.test_generation.review.completed": "Generated the test workspace from the approved drafts.",
        "process.test_generation.runtime.running": "Generating the test workspace using the provided runtime variables.",
        "process.test_generation.runtime.completed": "Generated the test workspace using the provided runtime variables.",
        "process.test_generation.modify.running": "Regenerating the test workspace from the updated drafts.",
        "process.test_generation.modify.completed": "Regenerated the test workspace from the updated drafts.",
        "process.modify.name": "Applying requested changes",
        "process.modify.running": "Reviewing your requested changes and updating the project artifacts...",
        "process.modify.completed": "Applied your requested changes and updated the project artifacts.",
        "status.no_human_feedback": "No human feedback in this round.",
        "status.generating_file": "Generating {file_name}.",
        "status.generated_file": "Generated {file_name}.",
        "status.code_pipeline_started": "Code generation pipeline started.",
        "status.code_pipeline_completed": "Code generation pipeline completed.",
    },
    "zh": {
        "artifact_review.title": "已生成草稿",
        "artifact_review.message": "核心草稿已生成。请先在右侧产物面板查看，确认后将进入代码生成；如需调整可继续修改。",
        "artifact_review.confirm": "确认草稿并开始生成代码",
        "artifact_review.cancel": "修改",
        "artifact_review.content": "请查看已生成草稿，并确认是否开始生成代码。",
        "artifact_review.option.prd.label": "PRD 草稿",
        "artifact_review.option.prd.description": "产品需求、范围与用户故事草稿。",
        "artifact_review.option.ui.label": "UI 草稿",
        "artifact_review.option.ui.description": "页面清单与核心交互草稿。",
        "artifact_review.option.architecture.label": "架构草稿",
        "artifact_review.option.architecture.description": "服务边界与技术架构草稿。",
        "artifact_review.option.api_spec.label": "API 设计",
        "artifact_review.option.api_spec.description": "核心后端 API 契约草稿。",
        "requirements_artifact_review.title": "需求草稿已生成",
        "requirements_artifact_review.message": "Requirements Agent 已完成需求源文件。请先查看主文件，确认后再继续进入 Architecture Agent。",
        "requirements_artifact_review.message_with_files": "Requirements Agent 已完成需求源文件。请先查看 {files}，确认后再继续进入 Architecture Agent。",
        "requirements_artifact_review.confirm": "确认需求草稿并继续生成架构",
        "requirements_artifact_review.cancel": "修改",
        "requirements_artifact_review.content": "请先查看已生成的需求源文件，并确认是否继续执行 Architecture Agent。",
        "input_variables.title": "配置运行时变量",
        "input_variables.message": "代码生成 Agent 继续执行真实编码流程前，需要先补充运行时配置。",
        "input_variables.submit": "继续",
        "input_variables.skip": "跳过并使用回退结果",
        "input_variables.content": "请提供继续代码生成所需的运行时变量。",
        "requirements_feedback.title": "需求 Agent 需要你的反馈",
        "requirements_feedback.message": "请先查看刚生成的主需求文件，再告诉 Agent 要改哪一段，以及会影响哪个文件。",
        "requirements_feedback.message_with_files": "请先查看 {files}，再告诉 Agent 要改哪一段，以及会影响哪个文件。",
        "requirements_feedback.field_label": "反馈内容",
        "requirements_feedback.placeholder": "填写要修改的内容。如果没有要改的，直接留空提交即可。",
        "requirements_feedback.submit": "提交反馈",
        "requirements_feedback.skip": "没有需要修改的地方",
        "requirements_feedback.content": "请查看生成的需求草稿，并把反馈提交给需求 Agent。",
        "requirements_feedback.resumed": "需求 Agent 已收到你的反馈，继续执行中",
        "coverage_conflict.title": "覆盖确认",
        "coverage_conflict.message": "此操作会覆盖当前项目产物，请确认后继续。",
        "coverage_conflict.option.label": "确认覆盖",
        "coverage_conflict.option.description": "继续执行，并用新的输出替换当前产物集。",
        "coverage_conflict.confirm": "确认覆盖",
        "coverage_conflict.cancel": "取消",
        "coverage_conflict.content": "请确认当前产物可以被覆盖后再继续。",
        "feature_modules.title": "功能模块",
        "feature_modules.confirm": "确认并继续",
        "feature_modules.cancel": "修改",
        "feature_modules.content": "请先查看 feature_tree.md，确认当前这版功能树是否可以继续用于后续生成。",
        "waiting.message": "Agent 正在等待你的响应",
        "task.completed.modify": "请求的修改已应用到最新项目草稿中。",
        "task.completed.review": "已根据确认后的草稿生成代码工作区，本轮任务完成。",
        "task.cancelled": "当前任务已取消。",
        "error.no_confirmed_modules": "当前项目还没有已确认的功能模块，请先完成首次生成流程。",
        "error.runtime_context_missing": "运行时变量请求缺少继续执行所需的上下文。",
        "error.runtime_resume_missing": "运行时变量请求无法恢复当前待处理任务。",
        "error.feedback_resume_direct_only": "这个等待步骤只能通过反馈表单恢复。",
        "error.feedback_context_missing": "当前待反馈的需求上下文已经丢失。",
        "error.feedback_session_missing": "等待中的需求 Agent 会话已经不存在了。",
        "error.overwrite_not_approved": "尚未确认覆盖当前产物，无法继续。",
        "error.pending_overwrite_missing": "找不到待处理的覆盖确认任务。",
        "error.unsupported_overwrite_task_type": "不支持任务类型 `{task_type}` 的覆盖确认流程。",
        "process.reading_context.name": "读取上下文",
        "process.reading_context.running": "正在读取提示词与已附加参考资料，准备开始分析。",
        "process.reading_context.completed": "已读取提示词与可用参考上下文。",
        "process.requirements_analysis.name": "分析需求",
        "process.requirements_analysis.running": "正在分析需求并提取建议的功能模块。",
        "process.requirements_analysis.completed": "已完成需求分析，并提取出建议的功能模块。",
        "process.artifact_generation.name": "生成核心产物",
        "process.artifact_generation.running": "正在生成用于评审的 PRD、UI、架构与 API 草稿。",
        "process.artifact_generation.completed": "已生成用于评审的 PRD、UI、架构与 API 草稿。",
        "process.requirements_drafts.name": "生成需求草稿文件",
        "process.requirements_drafts.running": "正在生成 PRD、UI、API 所需的需求草稿文件。",
        "process.requirements_drafts.waiting": "正在等待你的反馈，随后继续生成需求草稿文件。",
        "process.requirements_drafts.resumed": "已收到你的反馈，继续生成需求草稿文件。",
        "process.requirements_drafts.completed": "已生成需求草稿文件。",
        "process.requirements_artifact_review.name": "等待确认需求草稿",
        "process.requirements_artifact_review.waiting": "需求草稿已全部生成，确认后将进入架构阶段。",
        "process.architecture_generation.name": "生成架构草稿",
        "process.architecture_generation.running": "正在生成用于评审的架构草稿文件。",
        "process.architecture_generation.completed": "已生成架构草稿文件。",
        "process.artifact_review.name": "等待确认架构草稿",
        "process.artifact_review.waiting": "架构草稿已全部生成，确认后将进入 UI、代码和测试阶段。",
        "process.ui_generation.name": "生成 UI 工作区",
        "process.ui_generation.review.running": "正在根据已确认草稿生成 UI 工作区。",
        "process.ui_generation.review.completed": "已根据已确认草稿生成 UI 工作区。",
        "process.ui_generation.runtime.running": "正在使用提供的运行时变量生成 UI 工作区。",
        "process.ui_generation.runtime.completed": "已使用提供的运行时变量生成 UI 工作区。",
        "process.ui_generation.modify.running": "正在根据更新后的草稿重新生成 UI 工作区。",
        "process.ui_generation.modify.completed": "已根据更新后的草稿重新生成 UI 工作区。",
        "process.code_generation.name": "生成代码工作区",
        "process.code_generation.review.running": "正在根据已确认草稿生成后端代码工作区。",
        "process.code_generation.review.completed": "已根据已确认草稿生成后端代码工作区。",
        "process.code_generation.runtime.running": "正在使用提供的运行时变量生成后端代码工作区。",
        "process.code_generation.runtime.completed": "已使用提供的运行时变量生成后端代码工作区。",
        "process.code_generation.modify.running": "正在根据更新后的草稿重新生成后端代码工作区。",
        "process.code_generation.modify.completed": "已根据更新后的草稿重新生成后端代码工作区。",
        "process.test_generation.name": "生成测试工作区",
        "process.test_generation.review.running": "正在根据已确认草稿生成测试工作区。",
        "process.test_generation.review.completed": "已根据已确认草稿生成测试工作区。",
        "process.test_generation.runtime.running": "正在使用提供的运行时变量生成测试工作区。",
        "process.test_generation.runtime.completed": "已使用提供的运行时变量生成测试工作区。",
        "process.test_generation.modify.running": "正在根据更新后的草稿重新生成测试工作区。",
        "process.test_generation.modify.completed": "已根据更新后的草稿重新生成测试工作区。",
        "process.modify.name": "应用修改请求",
        "process.modify.running": "正在评估你的修改请求并更新项目产物……",
        "process.modify.completed": "已应用你的修改请求，并更新项目产物。",
        "status.no_human_feedback": "本轮没有人工反馈。",
        "status.generating_file": "正在生成 {file_name}。",
        "status.generated_file": "已生成 {file_name}。",
        "status.code_pipeline_started": "代码生成流程已开始。",
        "status.code_pipeline_completed": "代码生成流程已完成。",
    },
}


def normalize_locale(value: Any) -> Locale:
    if isinstance(value, str) and value.strip().lower().startswith("zh"):
        return "zh"
    return DEFAULT_LOCALE


def t(locale: Any, key: str, **kwargs: Any) -> str:
    normalized = normalize_locale(locale)
    template = _TRANSLATIONS.get(normalized, _TRANSLATIONS[DEFAULT_LOCALE]).get(key)
    if template is None:
        template = _TRANSLATIONS[DEFAULT_LOCALE].get(key, key)
    return template.format(**kwargs)
